Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import turtle
>>> t = turtle.Turtle()
>>> t.shape("turtle")
>>> t.forward(70)
>>> t.penup()
>>> t.forward(60)
>>> t.pendown()
>>> t.forward(70)
>>> t.right(108)
>>> t.right(36)
>>> t.forward(70)
>>> t.penup()
>>> t.forward(60)
>>> t.pendown()
>>> t.forward(70)
>>> t.right(144)
>>> t.forward(70)
>>> t.penup()
>>> t.forward(60)
>>> t.pendown()
>>> t.forward(70)
>>> t.right(144)
>>> t.forward(70)
>>> t.penup()
>>> t.forward(60)
>>> t.pendown()
>>> t.forward(70)
>>> t.right(144)
>>> t.forward(70)
>>> t.penup()
>>> t.forward(60)
>>> t.pendown()
>>> t.forward(70)
>>> 