score = [0,0,0,0,0]
score[0] = int(input("국어 점수는 "))
score[1] = int(input("수학 점수는 "))
score[2] = int(input("영어 점수는 "))
score[3] = int(input("과학 점수는 "))
score[4] = int(input("사회 점수는 "))
print("입력 자료 : ")
print(score)
print("정렬 자료 : ")
score.sort()
score.reverse()
print(score)
print("평균 점수 : ")
avg = (score[0] + score[1] + score[2] + score[3] + score[4])/5
print(avg)

import turtle
t = turtle.Turtle()
t.penup()
t.goto(-200,0)
t.pendown()
t.fillcolor("red")
t.penup()
t.circle(100,extent = 60)
t.pendown()
t.begin_fill()
t.circle(100,steps = 3)
t.end_fill()
t.penup()
t.goto(60,50)
t.circle(100,extent = 120)
t.pendown()
t.fillcolor("green")
t.begin_fill()
t.circle(100,steps = 3)
t.end_fill()
t.penup()
t.goto(145,200)
t.circle(100,extent=120)
t.pendown()
t.fillcolor("blue")
t.begin_fill()
t.circle(100,steps=3)
t.end_fill()
